This is full readme file
GSG-FC02/Quran-Apies pull request #13
Opened 2021-04-09 09:10 UTC by Ola014

Relates #2

2021-04-09 09:15 UTC, reemsh2000 approved these changes, later dismissed

2021-04-10 07:18 UTC, AlaaTaima commented on README.md
> +
This section have to be called : **The problem**

2021-04-10 07:27 UTC, AlaaTaima commented on README.md
> +
**here at user story try to make a list instead of a paragraph for the things that a user can do at your app.**

2021-04-10 07:31 UTC, AlaaTaima requested changes
**Good job 👍** 

but there are some points need to be enhanced.

2021-04-10 08:41 UTC, AlaaTaima approved these changes

2021-04-10 08:43 UTC, merged